#  auth_enabled: 指示是否启用身份验证。如果设置为 true，则需要在请求中提供有效的身份验证令牌。默认值为 false。
auth_enabled: false

#  server：指定 Loki 服务器的相关配置选项。常见的配置选项包括：
#  http_listen_port：Loki 服务器监听的 HTTP 端口号。默认为 3100。
#  grpc_listen_port：Loki 服务器监听的 gRPC 端口号。默认为 9095。
server:
  http_listen_port: 3100
  grpc_listen_port: 3110
  grpc_server_max_recv_msg_size: 1073741824  #grpc最大接收消息值，默认4m
  grpc_server_max_send_msg_size: 1073741824  #grpc最大发送消息值，默认4m

#  ingester：配置 Loki 的 Ingestor（数据摄取器）的相关选项。Ingestor 负责接收和处理日志数据。常见的配置选项包括：
#  lifecycler：指定 Ingestor 生命周期管理器的配置选项。
#  chunk_idle_period：定义 Ingestor 在将数据切片为块之前等待的时间。默认为 1h。
ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  max_transfer_retries: 0
  max_chunk_age: 20m  #一个timeseries块在内存中的最大持续时间。如果timeseries运行的时间超过此时间，则当前块将刷新到存储并创建一个新块

# schema_config：配置 Loki 的模式（Schema）配置选项。模式定义了数据存储的结构和索引方式。常见的配置选项包括：
# configs：指定不同日志源的模式配置。每个日志源可以有自己的模式配置。
schema_config:
  configs:
    - from: 2021-01-01
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 168h

# storage_config：配置 Loki 的存储后端的相关选项。存储后端负责持久化日志数据。常见的配置选项包括：
#  boltdb：指定使用 BoltDB 作为存储后端的配置选项。
storage_config:
  boltdb:
    directory: /opt/loki/index #存储索引地址
  filesystem:
    directory: /opt/loki/chunks
# limits_config：用于配置 Loki 的限制和配额选项。可以设置最大查询时间、最大行数等限制。
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  ingestion_rate_mb: 30  #修改每用户摄入速率限制，即每秒样本量，默认值为4M
  ingestion_burst_size_mb: 15  #修改每用户摄入速率限制，即每秒样本量，默认值为6M

# chunk_store_config：配置 Loki 的块存储后端的相关选项。
chunk_store_config:
  #max_look_back_period: 168h   #回看日志行的最大时间，只适用于即时日志
  max_look_back_period: 0s
# table_manager：配置 Loki 的表管理器的相关选项。表管理器负责创建和清理存储中的表。
table_manager:
  retention_deletes_enabled: false #日志保留周期开关，默认为false
  retention_period: 0s  #日志保留周期