kubeConfig: /Users/zhenyu.jiang/.kube/config   # k8s config目录，如果使用容器化部署，需要挂载kube config1
filterEventLevel:                               # 过滤的事件等级
elasticSearchEndpoint: http://127.0.0.1:9200    # es服务器endpoint
logFilePath: /Users/zhenyu.jiang/go/src/golanglearning/new_project/kube-event-collector   # 需要指定日志存放位置
# 通知模式：目前支持结构化日志、对接prometheus、发送email消息
mode:
  log: true
  prometheus: true
  message: true
  elasticSearch: false
# 邮箱配置信息
sender:
  remote: smtp.qq.com
  port:  25
  email: 2539512760@qq.com
  password: cswkxalurhtwecge
  targets: 3467320690@qq.com