kubeConfig: /Users/zhenyu.jiang/.kube/config    # k8s config目录，如果使用容器化部署，需要挂载kube config
filterEventLevel:                               # 过滤的事件等级
# 通知模式：目前支持结构化日志、对接prometheus、发送email消息
mode:
  log: true
  prometheus: true
  message: true
sender:
  remote: smtp.qq.com
  port:  25
  email: 2539512760@qq.com
  password: cswkxalurhtwecge
  targets: 3467320690@qq.com